env:
  browser: true
  commonjs: true
  es6: true
  node: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/camelcase':
    - off
  '@typescript-eslint/explicit-function-return-type':
    - off
  array-bracket-spacing:
    - error
    - always
  arrow-parens:
    - error
    - always
    - requireForBlockBody: false
  block-spacing:
    - error
    - always
  camelcase:
    - off
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - after: true
      before: false
        # indent:
        #   - error
        #   - 2
  linebreak-style:
    - error
    - unix
  no-console:
    - off
  no-multi-spaces:
    - off
  no-trailing-spaces:
    - error
  no-undef:
    - error
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  object-curly-spacing:
    - error
    - always
  padded-blocks:
    - error
    - never
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-before-blocks:
    - error
    - always
  keyword-spacing:
    - error
    - after: true
      before: true
